
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[271] =
    {   0,
       88,   88,    0,    0,    0,    0,    0,    0,   91,   89,
       88,   87,   89,   72,   11,    1,    2,   14,   12,    3,
       13,   89,   15,   85,    4,    6,   18,   35,   24,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,    7,    8,    9,   89,   10,   14,   84,   75,   90,
       73,   79,   78,   83,   81,   83,   88,   77,   16,    0,
        0,   86,    0,    0,    0,    0,    0,    0,    0,    0,
       80,   17,   28,   85,    5,   20,   26,   36,   22,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   44,   84,
       84,   84,   84,   84,   50,   84,   84,   84,   84,   84,

       84,   84,   84,   84,   84,   84,   76,   74,   82,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   46,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,    0,
       86,    0,   27,    0,    0,   23,   25,   21,   19,   29,
        0,    0,   31,    0,   37,   38,   84,   84,   84,   84,
       84,   42,   84,   45,   47,   84,   49,   84,   84,   84,
       84,   84,   84,   84,   65,   69,   84,   84,   84,   60,
       84,   64,   62,   30,   33,    0,    0,   32,    0,   84,

       39,   84,   84,   41,   84,   84,   84,   84,   84,   84,
       84,   53,   84,   84,   84,   84,   84,   84,    0,   34,
       71,   84,   66,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   58,   59,   84,   84,   84,
       84,   84,   67,   84,   68,   84,   55,   54,   84,   56,
       84,   84,   84,   40,   84,   48,   84,   84,   84,   84,
       84,   70,   43,   63,   52,   51,   57,   84,   61,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    1,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   31,   43,   44,   31,
       45,    1,   46,    1,    1,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   31,   31,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   31,   67,
       68,   31,   69,   70,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[275] =
    {   0,
        0,   62,   70,   71,  663,  662,   72,   75,  664,  667,
       77,  667,  659,  667,  667,  667,  667,  652,   73,  667,
       74,   96,   81,   78,  644,  667,  640,   63,  639,  642,
      145,   86,  130,   64,   79,  123,   97,  147,   83,  167,
      171,  667,  667,  667,   84,  667,   93,  653,  667,  667,
      650,  667,  667,  667,  667,  640,  102,  667,  667,  638,
      101,  152,   86,   90,   88,  165,  170,  176,  104,  133,
      667,  667,  667,  156,  667,  667,  667,  667,  667,  637,
      636,  198,  137,  163,  207,  196,  203,  217,  635,  208,
      201,  110,  212,  220,  634,  222,  228,  237,  233,  242,

      263,  236,  241,  232,  243,  257,  667,  667,  667,  291,
      241,  264,  257,  635,  634,  633,  632,  268,  250,  631,
      254,  292,  295,  280,  293,  282,  300,  304,  306,  307,
      315,  621,  309,  310,  319,  321,  322,  328,  329,  335,
      346,  351,  327,  339,  355,  349,  341,  366,  368,  620,
      618,  619,  667,  618,  347,  667,  667,  667,  667,  667,
      346,  617,  667,  363,  614,  613,  374,  382,  381,  375,
      397,  612,  386,  611,  608,  395,  607,  399,  401,  406,
      402,  413,  420,  416,  604,  602,  418,  422,  425,  599,
      410,  596,  595,  667,  667,  417,  595,  667,  594,  441,

      591,  439,  442,  590,  412,  451,  456,  467,  448,  463,
      470,  469,  477,  476,  471,  475,  472,  483,  591,  667,
      667,  488,  588,  489,  487,  497,  499,  500,  513,  495,
      502,  492,  522,  525,  523,  572,  569,  504,  539,  541,
      527,  515,  561,  550,  535,  544,  446,  431,  555,  415,
      530,  559,  560,  267,  563,  226,  565,  564,  568,  584,
      567,  174,  160,  142,  121,  109,  103,  587,   91,  667,
      638,  640,  642,   91
    } ;

static yyconst flex_int16_t yy_def[275] =
    {   0,
      270,    1,  271,  271,  272,  272,  273,  273,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  270,  270,  270,  270,  270,  270,   31,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  270,  270,  270,  270,  270,  270,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  270,  270,
      270,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,    0,
      270,  270,  270,  270
    } ;

static yyconst flex_int16_t yy_nxt[739] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   30,   31,   32,   33,   34,   35,   30,   36,
       30,   37,   30,   30,   30,   38,   30,   39,   40,   41,
       30,   30,   30,   30,   42,   43,   30,   30,   31,   32,
       33,   34,   35,   30,   36,   37,   30,   30,   30,   38,
       30,   39,   40,   41,   30,   30,   30,   30,   44,   45,
       46,   47,   50,   50,   55,   51,   51,   55,   57,   80,
       57,   56,   77,   78,   56,   48,   60,   60,   61,   61,
       71,   60,   81,   74,   80,   72,  107,   60,   80,   61,

       73,   80,   59,   57,   93,   57,   80,   87,  101,  113,
       48,   62,   80,   94,   60,   88,   61,   63,   80,  111,
       89,   64,   65,   66,   80,   80,  112,   67,   93,   68,
       69,   97,   87,  101,  113,   70,   80,   94,   80,  133,
       88,  120,   63,  111,   89,   80,   64,   65,   66,   95,
      112,   67,   80,   68,   69,   97,   96,   80,  124,   70,
       80,   90,   80,   91,  133,  120,   82,   62,   98,   60,
      121,   74,   92,   83,   95,   80,   84,  110,   80,   85,
       96,   99,   80,  124,  100,   90,   80,   91,   86,   80,
      114,   82,  102,   98,  121,  116,   92,  125,   83,  105,

       84,  118,  110,   85,  115,   99,  103,  104,  100,  117,
      119,   80,   86,   80,  106,  114,   80,  102,   80,  128,
      116,  125,   80,   80,  105,  132,  118,   80,  115,  122,
      103,  104,   80,  117,  119,   80,  123,   80,  106,  126,
      127,   80,  129,   80,  128,  134,  131,   80,   80,  130,
      132,   80,   80,  122,  147,  137,   80,   80,   80,  135,
      123,  136,  139,  126,  127,  152,  129,  145,  148,  134,
      131,  140,   80,  130,  138,  146,  141,  153,   80,  147,
      137,  160,   80,  135,  142,  136,  143,  139,  155,  162,
      152,  145,  149,  148,  164,   80,  140,   80,  138,  146,

      141,  150,  144,  150,  161,  154,  151,   80,   80,  142,
       80,  143,  155,  162,  169,   80,  149,  167,  164,   80,
      166,   80,   80,  165,   80,   80,  144,  172,  161,  154,
       80,  168,  173,  176,   80,  171,   80,   80,  169,  170,
      174,  167,   80,   80,   80,  166,  178,  165,  175,  180,
       80,  179,  172,  177,   80,  168,   80,  173,  176,  171,
      150,   80,  181,  170,   80,  174,   80,  187,  182,  183,
       80,  178,  175,  184,  180,  185,  179,  177,  191,  188,
      189,   80,  186,   80,  190,  196,  181,  197,  199,   80,
       80,  187,  182,  193,  183,  200,   80,   80,  184,  192,

      185,   80,  191,  188,  203,  189,  186,  201,  190,  196,
       80,  197,   80,  199,   80,  202,   80,   80,  193,  205,
      200,   80,  204,  192,  209,   80,  207,   80,   80,  203,
       80,   80,  201,   80,  206,   80,  208,   80,  210,  202,
       80,  211,  219,  205,  218,  213,   80,  204,  217,  209,
      225,  207,  212,  214,   80,  215,   80,   80,  206,  216,
      208,   80,  210,   80,  222,  211,   80,  219,  218,  229,
      213,   80,  223,  217,  225,  224,  212,  214,   80,  215,
      226,  227,   80,  216,   80,   80,   80,   80,  230,  222,
       80,   80,   80,  228,  229,  231,  223,  234,   80,  224,

      232,  233,   80,   80,   80,  226,  227,   80,  236,  235,
       80,  237,   80,  230,   80,   80,  241,   80,  228,   80,
      231,  244,  234,  238,  232,  248,  233,  239,   80,  240,
       80,  242,  236,  235,  246,  237,  243,   80,   80,  247,
       80,  241,   80,  252,  245,   80,  244,  238,  256,  248,
       80,  239,  251,  240,   80,  242,   80,  250,  246,   80,
      243,  255,  249,  247,  253,   80,  254,  252,  245,  258,
       80,  260,  256,  257,   80,   80,   80,  251,   80,   80,
       80,  250,   80,   80,   80,  255,  249,   80,  261,  253,
      264,  254,  259,  266,  258,  260,  263,  262,  257,   80,

      268,  265,   80,   80,  221,   80,   80,  221,  220,  267,
       80,   80,  269,  261,   80,  264,  259,   80,  266,   80,
      263,  262,   80,   80,  268,  265,   80,   80,   80,   80,
      198,  195,  194,  151,  267,  151,   80,  269,   49,   49,
       52,   52,   54,   54,  163,  159,  158,  157,  156,   80,
       80,   80,   80,   62,  109,  108,  107,   80,   79,   76,
       75,   59,   58,  270,   53,   53,    9,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270
    } ;

static yyconst flex_int16_t yy_chk[739] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    4,    7,    3,    4,    8,   11,   34,
       11,    7,   28,   28,    8,    2,   19,   21,   19,   21,
       23,   24,  274,   24,   35,   23,   47,   45,   39,   45,

       23,   32,   47,   57,   34,   57,  269,   32,   39,   65,
        2,   22,   37,   35,   61,   32,   61,   22,  267,   63,
       32,   22,   22,   22,  266,   92,   64,   22,   34,   22,
       22,   37,   32,   39,   65,   22,  265,   35,   36,   92,
       32,   69,   22,   63,   32,   33,   22,   22,   22,   36,
       64,   22,   83,   22,   22,   37,   36,  264,   83,   22,
       31,   33,   38,   33,   92,   69,   31,   62,   38,   74,
       70,   74,   33,   31,   36,  263,   31,   62,   84,   31,
       36,   38,   40,   83,   38,   33,   41,   33,   31,  262,
       66,   31,   40,   38,   70,   67,   33,   84,   31,   41,

       31,   68,   62,   31,   66,   38,   40,   40,   38,   67,
       68,   86,   31,   82,   41,   66,   91,   40,   87,   86,
       67,   84,   85,   90,   41,   91,   68,   93,   66,   82,
       40,   40,   88,   67,   68,   94,   82,   96,   41,   85,
       85,  256,   87,   97,   86,   93,   90,  104,   99,   88,
       91,  102,   98,   82,  104,   97,  103,  100,  105,   94,
       82,   96,   99,   85,   85,  111,   87,  102,  105,   93,
       90,  100,  106,   88,   98,  103,  100,  112,  101,  104,
       97,  118,  254,   94,  101,   96,  101,   99,  113,  119,
      111,  102,  106,  105,  121,  124,  100,  126,   98,  103,

      100,  110,  101,  110,  118,  112,  110,  122,  125,  101,
      123,  101,  113,  119,  126,  127,  106,  124,  121,  128,
      123,  129,  130,  122,  133,  134,  101,  129,  118,  112,
      131,  125,  130,  134,  135,  128,  136,  137,  126,  127,
      131,  124,  143,  138,  139,  123,  136,  122,  133,  138,
      140,  137,  129,  135,  144,  125,  147,  130,  134,  128,
      110,  141,  139,  127,  146,  131,  142,  143,  140,  141,
      145,  136,  133,  141,  138,  142,  137,  135,  147,  144,
      145,  148,  142,  149,  146,  155,  139,  161,  164,  167,
      170,  143,  140,  149,  141,  167,  169,  168,  141,  148,

      142,  173,  147,  144,  170,  145,  142,  168,  146,  155,
      176,  161,  171,  164,  178,  169,  179,  181,  149,  173,
      167,  180,  171,  148,  179,  191,  178,  205,  182,  170,
      250,  184,  168,  187,  176,  183,  178,  188,  180,  169,
      189,  181,  196,  173,  191,  183,  248,  171,  189,  179,
      205,  178,  182,  184,  202,  187,  200,  203,  176,  188,
      178,  247,  180,  209,  200,  181,  206,  196,  191,  209,
      183,  207,  202,  189,  205,  203,  182,  184,  210,  187,
      206,  207,  208,  188,  212,  211,  215,  217,  210,  200,
      216,  214,  213,  208,  209,  211,  202,  214,  218,  203,

      212,  213,  225,  222,  224,  206,  207,  232,  216,  215,
      230,  217,  226,  210,  227,  228,  225,  231,  208,  238,
      211,  228,  214,  218,  212,  232,  213,  222,  229,  224,
      242,  226,  216,  215,  230,  217,  227,  233,  235,  231,
      234,  225,  241,  238,  229,  251,  228,  218,  242,  232,
      245,  222,  235,  224,  239,  226,  240,  234,  230,  246,
      227,  241,  233,  231,  239,  244,  240,  238,  229,  246,
      249,  251,  242,  244,  252,  253,  243,  235,  255,  258,
      257,  234,  261,  259,  237,  241,  233,  236,  252,  239,
      257,  240,  249,  259,  246,  251,  255,  253,  244,  260,

      261,  258,  268,  223,  219,  204,  201,  199,  197,  260,
      193,  192,  268,  252,  190,  257,  249,  186,  259,  185,
      255,  253,  177,  175,  261,  258,  174,  172,  166,  165,
      162,  154,  152,  151,  260,  150,  132,  268,  271,  271,
      272,  272,  273,  273,  120,  117,  116,  115,  114,   95,
       89,   81,   80,   60,   56,   51,   48,   30,   29,   27,
       25,   18,   13,    9,    6,    5,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 3 "lex.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"
	
#define LIST     strcat(buf,yytext)
#define token(t) {LIST; printf("<%s>\n",t);}
#define tokenInteger(t,i) {LIST; printf("<%s:%d>\n",t,i);}
#define tokenString(t,s) {LIST; printf("<%s:%s>\n",t,s);}

#define MAX_LINE_LENG 256

int linenum = 1;
char buf[MAX_LINE_LENG];

/* Used to State<STRING>
   This buffer is contain string that is copy from yytext.
   Pointer s is point to buffer "strBuf". */
char strBuf[MAX_LINE_LENG];
char *s;




#line 736 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT1 2
#define COMMENT2 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 35 "lex.l"

 /* Define Delimiters */
#line 932 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 271 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 667 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "lex.l"
{LIST; return CCOLON;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
/* Define Component Reference */
case 11:
YY_RULE_SETUP
#line 49 "lex.l"
{LIST; return PERCENT;}
	YY_BREAK
/* Define Arithmetic */
case 12:
YY_RULE_SETUP
#line 52 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
/* Define Exponentiation */
case 16:
YY_RULE_SETUP
#line 58 "lex.l"
{LIST; return EXP;}
	YY_BREAK
/* Define Concatentation */
case 17:
YY_RULE_SETUP
#line 61 "lex.l"
{LIST; return CONCAT;}
	YY_BREAK
/* Define Relational */
case 18:
YY_RULE_SETUP
#line 64 "lex.l"
{LIST; return LT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "lex.l"
{LIST; return LT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "lex.l"
{LIST; return LE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "lex.l"
{LIST; return LE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "lex.l"
{LIST; return GE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "lex.l"
{LIST; return GE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "lex.l"
{LIST; return GT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "lex.l"
{LIST; return GT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "lex.l"
{LIST; return EQ;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "lex.l"
{LIST; return EQ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "lex.l"
{LIST; return NE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "lex.l"
{LIST; return NE;}
	YY_BREAK
/* Define Logical */
case 30:
YY_RULE_SETUP
#line 78 "lex.l"
{LIST; return AND;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "lex.l"
{LIST; return OR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "lex.l"
{LIST; return NOT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "lex.l"
{LIST; return EQV;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "lex.l"
{LIST; return NEQV;}
	YY_BREAK
/* Define Assignment */
case 35:
YY_RULE_SETUP
#line 85 "lex.l"
{LIST; return *yytext;}
	YY_BREAK
/* Define Pointer Assignment */
case 36:
YY_RULE_SETUP
#line 88 "lex.l"
{LIST; return PASSIGNMENT;}
	YY_BREAK
/* Define Keywords */
case 37:
YY_RULE_SETUP
#line 91 "lex.l"
{LIST; return CALL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "lex.l"
{LIST; return CASE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "lex.l"
{LIST; return CLOSE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "lex.l"
{LIST; return CONTINUE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "lex.l"
{LIST; return CYCLE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 96 "lex.l"
{LIST; return DATA;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 97 "lex.l"
{LIST; return DIMENSION;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 98 "lex.l"
{LIST; return DO;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 99 "lex.l"
{LIST; return ELSE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 100 "lex.l"
{LIST; return END;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 101 "lex.l"
{LIST; return EXIT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 102 "lex.l"
{LIST; return FUNCTION;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 103 "lex.l"
{LIST; return GOTO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 104 "lex.l"
{LIST; return IF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 105 "lex.l"
{LIST; return PROCEDURE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 106 "lex.l"
{LIST; return PARAMETER;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 107 "lex.l"
{LIST; return PRINT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 108 "lex.l"
{LIST; return PRINTLN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 109 "lex.l"
{LIST; return POINTER;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 110 "lex.l"
{LIST; return PROGRAM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 111 "lex.l"
{LIST; return RECURSIVE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 112 "lex.l"
{LIST; return RETURN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "lex.l"
{LIST; return SELECT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 114 "lex.l"
{LIST; return STOP;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 115 "lex.l"
{LIST; return SUBROUTINE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "lex.l"
{LIST; return TYPE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 117 "lex.l"
{LIST; return INTERFACE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "lex.l"
{LIST; return THEN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 119 "lex.l"
{LIST; return READ;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 120 "lex.l"
{LIST; return COMMON;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 122 "lex.l"
{LIST; return INTEGER;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 123 "lex.l"
{LIST; return LOGICAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 124 "lex.l"
{LIST; return REAL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 125 "lex.l"
{LIST; return CHARACTER;}
	YY_BREAK
/* Boolean Constants */
case 71:
YY_RULE_SETUP
#line 128 "lex.l"
{
                LIST; 
				if(!strcmp(".TRUE.", yytext))
				 yylval.bval = 1;
				else
				 yylval.bval = 0;
					
				return LOGICALC;	
				}
	YY_BREAK
/* State<STRING> is for String Constants */
case 72:
YY_RULE_SETUP
#line 139 "lex.l"
{
				LIST;
				BEGIN(STRING);
				s = strBuf;
				}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 145 "lex.l"
{
                LIST;
				*s = 0;
				BEGIN 0;
				yylval.sval = strdup(strBuf);
				return STRINGC;
				}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "lex.l"
{
				LIST;
				*s++ = '"';
				}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 158 "lex.l"
{
				LIST;
				*s++ = *yytext;
				}
	YY_BREAK
/* State<COMMENT1> (for C * !) */
case 76:
YY_RULE_SETUP
#line 164 "lex.l"
{LIST;	BEGIN(COMMENT1);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "lex.l"
{LIST; BEGIN(COMMENT1);}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 166 "lex.l"
{
			yyless(yyleng-1);
			BEGIN 0;
			}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 170 "lex.l"
{LIST;}
	YY_BREAK
/* State<COMMENT2> (for star symbol comment) */
case 80:
YY_RULE_SETUP
#line 173 "lex.l"
{
			BEGIN(COMMENT2);
			}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 176 "lex.l"
{
			printf("%d: %s\n", linenum++, buf);
			buf[0] = 0;
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 180 "lex.l"
{
			LIST;
			BEGIN 0;
			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 184 "lex.l"
{LIST;}
	YY_BREAK
/* Identifiers */
case 84:
YY_RULE_SETUP
#line 189 "lex.l"
{
            LIST; 
	   		char* s = (char*)malloc(yyleng*sizeof(char));
			strcpy(s, yytext);
            yylval.sval = strdup(yytext);	 
			return ID;
			}
	YY_BREAK
/* Integer Constant */
case 85:
YY_RULE_SETUP
#line 198 "lex.l"
{
            LIST; 
			yylval.ival = atoi(yytext);
			return INTEGERC;
		   	}
	YY_BREAK
/* Real Constant */
case 86:
YY_RULE_SETUP
#line 205 "lex.l"
{
            LIST; 
	        yylval.dval = atof(yytext);
			return REALC;
			}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 211 "lex.l"
{
			LIST;
			printf("%d: %s", linenum++, buf);
			buf[0] = '\0';
            yyless(1);
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 219 "lex.l"
{LIST;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 222 "lex.l"
{
			LIST;
			printf("%d:%s\n", linenum+1, buf);
			printf("bad character:'%s'\n",yytext);
			exit(-1);
			}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 229 "lex.l"
ECHO;
	YY_BREAK
#line 1544 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENT1):
case YY_STATE_EOF(COMMENT2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 271 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 271 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 270);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 229 "lex.l"



void yyerror (const char const *s) {
   fprintf (stderr, "line(%d)>token(%s).errMsg:%s\n", linenum, yytext, s);
   exit(EXIT_FAILURE);
}

int yywrap()
{
	return 1;
}

